efficientnet:
  model_name: "efficientnet-b3"
  val_split: 0.15
  learning_rate: 0.001 # 1e-3 # 1e-4
  batch_size: 5
  max_epochs: 20
  early_stopping_patience: 3
  normalize:
    rgb_means: [0.41210787, 0.50030631, 0.34875169]
    rgb_stds: [0.15202952, 0.15280726, 0.1288698]
  transforms:
    height: 1024
    width: 1024
    blur_kernel:  5
    blur_probability: 0.3
    horizontal_flip_probability: 0.5
    vertical_flip_probability: 0.5
